### ISSUE TITLE
Hostname fallback when searching

### ISSUE THREAD

**Issue by mjanser** [gekmihesg/pass-manager#4]
Some websites use www.[domain].[tld] as their hostnames and other have special hostnames for login like accounts.[domain].[tld]. I'd like to store the passwords for them without the prefixes, but just the domain. The addon doesn't find the passwords then because the hostname doesn't match exactly. Is it possible to support such a fallback to the domain? Maybe with a config option?

**Comment by gekmihesg** [comment]
Good idea, thanks. Implemented in 87362fa73b8b80c40bc14906782208813a6c166d.
